// <auto-generated />
using BookstoreRepository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookstoreRepository.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200530120645_customer")]
    partial class customer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookstoreModel.Model.BookModel", b =>
                {
                    b.Property<int>("Bookid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Bookname");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int>("Price");

                    b.Property<string>("Review");

                    b.HasKey("Bookid");

                    b.ToTable("BookTable");
                });

            modelBuilder.Entity("BookstoreModel.Model.CartModel", b =>
                {
                    b.Property<long>("Cartid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Bookid");

                    b.Property<int>("Count");

                    b.HasKey("Cartid");

                    b.ToTable("CartTable");
                });

            modelBuilder.Entity("BookstoreModel.Model.CustomerModel", b =>
                {
                    b.Property<int>("Customerid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Emailid");

                    b.Property<string>("LandMark");

                    b.Property<int>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<int>("PinCode");

                    b.HasKey("Customerid");

                    b.ToTable("CustomerTable");
                });

            modelBuilder.Entity("BookstoreModel.Model.UserModel", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emailid");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Userid");

                    b.ToTable("UserTable");
                });
#pragma warning restore 612, 618
        }
    }
}
